name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - master # Or your desired branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          # If your repository name is not the same as the base path,
          # you might need to set a CNAME or adjust the base path in next.config.js
          # cname: example.com
